services:
  postgres:
    image: postgres:18
    container_name: swallie-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: swallie
      POSTGRES_USER: swallie
      POSTGRES_PASSWORD: swallie_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  redis:
    image: redis:8
    container_name: swallie-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/redis/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_HOST: postgres
    container_name: swallie-backend
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8000:8000"

  frontend-admin:
    build:
      context: .
      dockerfile: frontend-admin/Dockerfile
    container_name: swallie-frontend-admin
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data: