"""add constraints

Revision ID: 8797a9eb547b
Revises: f437e85e6b0a
Create Date: 2026-08-26 19:47:46.704584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8797a9eb547b'
down_revision: Union[str, Sequence[str], None] = 'f437e85e6b0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_producer_producer_name', 'producers', ['producer_name'])
    op.create_unique_constraint('uq_product_size_per_product', 'product_variants', ['product_id', 'product_size'])
    op.create_unique_constraint('uq_product_product_name', 'products', ['product_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_product_product_name', 'products', type_='unique')
    op.drop_constraint('uq_product_size_per_product', 'product_variants', type_='unique')
    op.drop_constraint('uq_producer_producer_name', 'producers', type_='unique')
    # ### end Alembic commands ###
