"""order items

Revision ID: ee28a76a6cbc
Revises: 17b01c9b0447
Create Date: 2026-08-11 10:38:39.399077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee28a76a6cbc'
down_revision: Union[str, Sequence[str], None] = '17b01c9b0447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


product_size_enum = sa.Enum(
    'Can 330ml',
    'Can 440ml',
    'Bottle 330ml',
    'Bottle 500ml',
    'Pint 1/3rd',
    'Pint 1/2',
    'Pint',
    name='productsize',
)


def upgrade() -> None:
    """Upgrade schema."""
    product_size_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_size',
               existing_type=sa.VARCHAR(length=100),
               type_=product_size_enum,
               existing_nullable=False,
               postgresql_using='product_size::text::productsize')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'product_size',
               existing_type=product_size_enum,
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               postgresql_using='product_size::text')

    product_size_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
