"""products

Revision ID: f437e85e6b0a
Revises: 2c61026b5d17
Create Date: 2026-08-11 18:03:09.600508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f437e85e6b0a'
down_revision: Union[str, Sequence[str], None] = '2c61026b5d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'abv',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'abv',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               nullable=False)
    # ### end Alembic commands ###
